spring:
  application:
    name: my-springboot-project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resource_sharing
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.content.my_springboot_project.model

file:
  pagination:
    page-size: 20
  img:
    avatarPath: E:/VSCodeWarehouse/JavaProjects/springboot/my-springboot-project/warehouse/avatars/
    introduceImgs: E:/VSCodeWarehouse/JavaProjects/springboot/my-springboot-project/warehouse/introduceImgs/
